# Generated by Django 5.0.4 on 2024-05-03 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Giocatore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('velocita', models.IntegerField(default=1)),
                ('tiro', models.IntegerField(default=1)),
                ('passaggio', models.IntegerField(default=1)),
                ('dribbling', models.IntegerField(default=1)),
                ('difesa', models.IntegerField(default=1)),
                ('fisico', models.IntegerField(default=1)),
                ('ruolo', models.CharField(choices=[('P', 'Portiere'), ('D', 'Difensore'), ('C', 'Centrocampista'), ('A', 'Attaccante')], max_length=1)),
                ('overall', models.DecimalField(decimal_places=2, max_digits=5)),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
