# Generated by Django 5.0.4 on 2024-05-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicazione_du', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giocatore',
            name='utente',
        ),
        migrations.AlterField(
            model_name='giocatore',
            name='overall',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
