# Generated by Django 5.0.4 on 2024-05-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicazione_du', '0002_remove_giocatore_utente_alter_giocatore_overall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giocatore',
            name='overall',
            field=models.IntegerField(default=1),
        ),
    ]
